import type { RemotionNarrativeBundle } from '../utils/remotion-bundle';

export function createFallbackRemotionBundle(): RemotionNarrativeBundle {
  return {
    schemaVersion: 'remotion-narrative-v1',
    sourceSystem: 'multi-dimension-profiling',
    exportedAt: new Date(0).toISOString(),
    title: '画像揭示片',
    subtitle: '等待真实画像结果注入',
    fps: 30,
    durationSec: 6,
    defaultCompositionId: 'portrait-reveal',
    compositions: [
      {
        id: 'portrait-reveal',
        name: 'Portrait Reveal',
        width: 1080,
        height: 1920,
        fps: 30,
        durationInFrames: 180,
        purpose: '短视频分享 / 结果揭示 / 手机端传播',
      },
      {
        id: 'landscape-brief',
        name: 'Landscape Brief',
        width: 1920,
        height: 1080,
        fps: 30,
        durationInFrames: 180,
        purpose: '演示汇报 / 桌面展示 / 官网嵌入',
      },
    ],
    themeTokens: {
      tone: 'analytical',
      primary: '#64FFDA',
      secondary: '#BB86FC',
      accent: '#FFD166',
      background: '#06131A',
      surface: 'rgba(10, 30, 38, 0.72)',
      textPrimary: '#F5FFFD',
      textSecondary: 'rgba(220, 246, 242, 0.76)',
      gradient: 'linear-gradient(135deg, #64FFDA 0%, #BB86FC 55%, #FFD166 100%)',
    },
    dataSnapshot: {
      archetype: '等待生成',
      currentFocus: '等待真实画像输入',
      longTermVision: '等待真实画像输入',
      mission: '等待真实画像输入',
      topDimensions: [],
      crossReactions: [],
      recommendedResearchTopics: [],
      productConcepts: [],
    },
    sceneOutline: [
      {
        id: 'archetype-reveal',
        title: '原型揭示',
        startSec: 0,
        endSec: 6,
        durationSec: 6,
        purpose: '等待真实画像结果',
        compositionHint: 'hero',
        transition: 'glow',
        headline: '等待真实画像结果',
        supportingLines: ['当你完成测评后，这里会长出属于你的真实叙事片。'],
        visualDirection: '以柔和的底色和标题作为占位。',
        motionNotes: ['默认淡入', '等待真实镜头数据'],
        dataRefs: [],
      },
    ],
    captionBlocks: [
      {
        id: 'fallback-caption',
        sceneId: 'archetype-reveal',
        startSec: 0,
        endSec: 6,
        text: '等待真实画像结果',
        style: 'headline',
      },
    ],
    voiceoverScript: [
      {
        sceneId: 'archetype-reveal',
        startSec: 0,
        endSec: 6,
        pace: 'slow',
        text: '等待真实画像结果。',
      },
    ],
    visualMotifs: [
      {
        id: 'fallback-motif',
        label: '默认光场',
        description: '作为 composition 初始化时的默认占位。',
        colors: ['#64FFDA', '#BB86FC'],
        motionStyle: 'bloom',
        keywords: ['等待输入'],
        assetSuggestions: ['柔和渐变底色'],
      },
    ],
    audioDirection: {
      mood: '冷静等待',
      bpmRange: '72-80',
      texture: 'ambient pad',
      cues: ['等待真实音轨'],
    },
    remotionProps: {
      title: '画像揭示片',
      subtitle: '等待真实画像结果注入',
      themeTokens: {
        tone: 'analytical',
        primary: '#64FFDA',
        secondary: '#BB86FC',
        accent: '#FFD166',
        background: '#06131A',
        surface: 'rgba(10, 30, 38, 0.72)',
        textPrimary: '#F5FFFD',
        textSecondary: 'rgba(220, 246, 242, 0.76)',
        gradient: 'linear-gradient(135deg, #64FFDA 0%, #BB86FC 55%, #FFD166 100%)',
      },
      scenes: [
        {
          id: 'archetype-reveal',
          title: '原型揭示',
          startSec: 0,
          endSec: 6,
          durationSec: 6,
          purpose: '等待真实画像结果',
          compositionHint: 'hero',
          transition: 'glow',
          headline: '等待真实画像结果',
          supportingLines: ['当你完成测评后，这里会长出属于你的真实叙事片。'],
          visualDirection: '以柔和的底色和标题作为占位。',
          motionNotes: ['默认淡入', '等待真实镜头数据'],
          dataRefs: [],
        },
      ],
      captions: [
        {
          id: 'fallback-caption',
          sceneId: 'archetype-reveal',
          startSec: 0,
          endSec: 6,
          text: '等待真实画像结果',
          style: 'headline',
        },
      ],
      voiceover: [
        {
          sceneId: 'archetype-reveal',
          startSec: 0,
          endSec: 6,
          pace: 'slow',
          text: '等待真实画像结果。',
        },
      ],
      highlightMetrics: {
        topConfidence: 0,
        crossReactionCount: 0,
        researchTopicCount: 0,
      },
    },
    bridge: {
      openbasakaBundle: {
        bossCore: {
          headline: '等待真实画像结果',
          currentFocus: '',
          longTermVision: '',
          mission: '',
          preferredStyle: 'analytical',
          resourceStyle: 'balanced',
          decisionSpeed: 'deliberate',
          riskTolerance: 50,
          innovationBias: 50,
          socialEnergy: 50,
          executionDiscipline: 50,
          emotionalSensitivity: 50,
          aestheticSensitivity: 50,
          curiosityBreadth: 50,
          worldviewDrive: 50,
          explanationPreferences: [],
          excitementTriggers: [],
          antiPatterns: [],
          integrationGoals: [],
          recommendedAgents: [],
          recommendedResearchTopics: [],
          promptSummary: '等待真实画像结果',
          evidenceTrace: [],
        },
      },
      fusedProfileBundle: {
        topology: {
          id: 'fallback-topology',
          selfArchetype: '等待生成',
          narrativeIdentity: '等待真实画像结果注入。',
          dimensionTopologies: {},
          crossReactions: [],
          confidenceMap: {},
          pendingVerification: [],
          createdAt: new Date(0).toISOString(),
        },
        sageInsights: [],
        personalOS: null,
        productJobs: [],
        productConcepts: [],
        implementationPlans: [],
        aiSummary: '',
      },
    },
  };
}
